/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Essay = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'isFeatured' : IDL.Bool,
  'publicationDate' : IDL.Int,
  'excerpt' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'linkedIn' : IDL.Text,
  'email' : IDL.Text,
  'bluesky' : IDL.Text,
});
export const PageContent = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subtitle' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEssay' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Int],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEssay' : IDL.Func([IDL.Nat], [], []),
  'getAllEssays' : IDL.Func([], [IDL.Vec(Essay)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], []),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getFeaturedEssay' : IDL.Func([], [IDL.Opt(Essay)], ['query']),
  'getPageContent' : IDL.Func([IDL.Text], [PageContent], ['query']),
  'getSiteBranding' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFeaturedEssay' : IDL.Func([IDL.Nat], [], []),
  'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateEssay' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Int],
      [],
      [],
    ),
  'updatePageContent' : IDL.Func([IDL.Text, PageContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Essay = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'isFeatured' : IDL.Bool,
    'publicationDate' : IDL.Int,
    'excerpt' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'linkedIn' : IDL.Text,
    'email' : IDL.Text,
    'bluesky' : IDL.Text,
  });
  const PageContent = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  
  return IDL.Service({
    'addEssay' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Int],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEssay' : IDL.Func([IDL.Nat], [], []),
    'getAllEssays' : IDL.Func([], [IDL.Vec(Essay)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], []),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getFeaturedEssay' : IDL.Func([], [IDL.Opt(Essay)], ['query']),
    'getPageContent' : IDL.Func([IDL.Text], [PageContent], ['query']),
    'getSiteBranding' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFeaturedEssay' : IDL.Func([IDL.Nat], [], []),
    'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateEssay' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Int],
        [],
        [],
      ),
    'updatePageContent' : IDL.Func([IDL.Text, PageContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };